[workspace]
members = ["src/ic_side_services_akash_backend", "src/ic_tendermint_rpc"]
resolver = "2"

[workspace.dependencies]
candid = "0.9.3"
ic-cdk = "0.10.0"
serde = "1.0.195"
serde_json = { version = "1.0.111", features = ["preserve_order"] }
hex = "0.4.3"
sha2 = "0.10.8"
